// <auto-generated />
using System;
using DispatchService.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DispatchService.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(DispatchServiceDbContext))]
    [Migration("20250529171507_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DispatchService.Domain.Model.DailySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Route")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("DailySchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverId = 1,
                            EndTime = new DateTime(2025, 5, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Route = "52",
                            StartTime = new DateTime(2025, 5, 15, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            DriverId = 2,
                            EndTime = new DateTime(2025, 5, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Route = "52",
                            StartTime = new DateTime(2025, 5, 15, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 3,
                            DriverId = 3,
                            EndTime = new DateTime(2025, 5, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Route = "52",
                            StartTime = new DateTime(2025, 5, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 4,
                            DriverId = 4,
                            EndTime = new DateTime(2025, 5, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Route = "52",
                            StartTime = new DateTime(2025, 5, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 4
                        },
                        new
                        {
                            Id = 5,
                            DriverId = 5,
                            EndTime = new DateTime(2025, 5, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Route = "52",
                            StartTime = new DateTime(2025, 5, 15, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 5
                        },
                        new
                        {
                            Id = 6,
                            DriverId = 6,
                            EndTime = new DateTime(2025, 5, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Route = "52",
                            StartTime = new DateTime(2025, 5, 15, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 6
                        },
                        new
                        {
                            Id = 7,
                            DriverId = 1,
                            EndTime = new DateTime(2025, 5, 25, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Route = "52",
                            StartTime = new DateTime(2025, 5, 25, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 8,
                            DriverId = 1,
                            EndTime = new DateTime(2025, 5, 20, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Route = "52",
                            StartTime = new DateTime(2025, 5, 20, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 9,
                            DriverId = 2,
                            EndTime = new DateTime(2025, 5, 25, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Route = "52",
                            StartTime = new DateTime(2025, 5, 25, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 10,
                            DriverId = 2,
                            EndTime = new DateTime(2025, 5, 20, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Route = "52",
                            StartTime = new DateTime(2025, 5, 20, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 11,
                            DriverId = 4,
                            EndTime = new DateTime(2025, 5, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Route = "52",
                            StartTime = new DateTime(2025, 5, 15, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 4
                        },
                        new
                        {
                            Id = 12,
                            DriverId = 5,
                            EndTime = new DateTime(2025, 5, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Route = "52",
                            StartTime = new DateTime(2025, 5, 15, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 5
                        });
                });

            modelBuilder.Entity("DispatchService.Domain.Model.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("DriverLicense")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Passport")
                        .HasColumnType("longtext");

                    b.Property<string>("Patronymic")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Улица Пушкина Дом Колотушкина",
                            DriverLicense = "11 22 345678",
                            FirstName = "Иван",
                            LastName = "Иванов",
                            Passport = "1122 345678",
                            Patronymic = "Иванович",
                            Phone = "+74950198687"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Улица Пушкина Дом Колотушкина",
                            DriverLicense = "11 22 345678",
                            FirstName = "Иван",
                            LastName = "Федоров",
                            Passport = "1122 345678",
                            Patronymic = "Васильевич",
                            Phone = "+74950198687"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Улица Пушкина Дом Колотушкина",
                            DriverLicense = "11 22 345678",
                            FirstName = "Дмитрий",
                            LastName = "Петров",
                            Passport = "1122 345678",
                            Patronymic = "Иванович",
                            Phone = "+74950198687"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Улица Пушкина Дом Колотушкина",
                            DriverLicense = "11 22 345678",
                            FirstName = "Василий",
                            LastName = "Сидоров",
                            Passport = "1122 345678",
                            Patronymic = "Дмитриевич",
                            Phone = "+74950198687"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Улица Пушкина Дом Колотушкина",
                            DriverLicense = "11 22 345678",
                            FirstName = "Константин",
                            LastName = "Иванов",
                            Passport = "1122 345678",
                            Patronymic = "Николаевич",
                            Phone = "+74950198687"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Улица Пушкина Дом Колотушкина",
                            DriverLicense = "11 22 345678",
                            FirstName = "Иван",
                            LastName = "Фролов",
                            Passport = "1122 345678",
                            Patronymic = "Дмитриевич",
                            Phone = "+74950198687"
                        });
                });

            modelBuilder.Entity("DispatchService.Domain.Model.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LicensePlate")
                        .HasColumnType("longtext");

                    b.Property<int?>("VehicleModelId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("YearOfManufacture")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LicensePlate = "A123AA63",
                            VehicleModelId = 1,
                            VehicleType = "Bus",
                            YearOfManufacture = 2020
                        },
                        new
                        {
                            Id = 2,
                            LicensePlate = "A123AA63",
                            VehicleModelId = 3,
                            VehicleType = "Trolleybus",
                            YearOfManufacture = 2022
                        },
                        new
                        {
                            Id = 3,
                            LicensePlate = "A123AA63",
                            VehicleModelId = 4,
                            VehicleType = "Tram",
                            YearOfManufacture = 2021
                        },
                        new
                        {
                            Id = 4,
                            LicensePlate = "A123AA63",
                            VehicleModelId = 2,
                            VehicleType = "Bus",
                            YearOfManufacture = 2023
                        },
                        new
                        {
                            Id = 5,
                            LicensePlate = "A123AA63",
                            VehicleModelId = 3,
                            VehicleType = "Trolleybus",
                            YearOfManufacture = 2024
                        },
                        new
                        {
                            Id = 6,
                            LicensePlate = "A123AA63",
                            VehicleModelId = 5,
                            VehicleType = "Tram",
                            YearOfManufacture = 2021
                        });
                });

            modelBuilder.Entity("DispatchService.Domain.Model.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLowFloor")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsLowFloor = true,
                            MaxCapacity = 82,
                            ModelName = "ЛиАЗ 4292"
                        },
                        new
                        {
                            Id = 2,
                            IsLowFloor = true,
                            MaxCapacity = 117,
                            ModelName = "ЛиАЗ 5292"
                        },
                        new
                        {
                            Id = 3,
                            IsLowFloor = true,
                            MaxCapacity = 100,
                            ModelName = "Адмирал 2022"
                        },
                        new
                        {
                            Id = 4,
                            IsLowFloor = true,
                            MaxCapacity = 184,
                            ModelName = "Богатырь-М"
                        },
                        new
                        {
                            Id = 5,
                            IsLowFloor = true,
                            MaxCapacity = 255,
                            ModelName = "Витязь-Ленинград"
                        },
                        new
                        {
                            Id = 6,
                            IsLowFloor = true,
                            MaxCapacity = 190,
                            ModelName = "ЛиАЗ 6213"
                        });
                });

            modelBuilder.Entity("DispatchService.Domain.Model.DailySchedule", b =>
                {
                    b.HasOne("DispatchService.Domain.Model.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DispatchService.Domain.Model.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DispatchService.Domain.Model.Vehicle", b =>
                {
                    b.HasOne("DispatchService.Domain.Model.VehicleModel", null)
                        .WithMany()
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
